### ðŸ’« Enhancements and new features

- `Constraint` implementations now raise `ConstraintError` consistently
  on a violation. This now makes it possible to distinguish properly
  handled violations from improper implementation of such checks.
  Moreover, `raise_for()` is now used consistently, providing
  uniform, structured information on such violations.
  `ConstraintError` is derived from `ValueError` (the exception
  that was previously (mostly) raised. Therefore, client-code should
  continue to work without modification, unless a specific wording
  of an exception message is relied upon. In few cases, an implicit
  `TypeError` (e.g., `EnsureIterableof`) has been replaced by an
  explicit `ConstraintError`, and client code needs to be adjusted.
  The underlying exception continues to be available via
  `ConstraintError.caused_by`. (by @mih)
